Reduce duplication in workflow using composite action

diff --git a/.github/workflows/live_snyk_scan.yml b/.github/workflows/live_snyk_scan.yml
--- a/.github/workflows/live_snyk_scan.yml
+++ b/.github/workflows/live_snyk_scan.yml
@@ -76,21 +76,10 @@ jobs:
         with:
           fetch-depth: 1
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
+      - name: Load docker image from registry
+        uses: cyber-dojo/load-image-from-registry@main
         with:
-          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions_live_snyk_scans
-          aws-region: ${{ env.AWS_REGION }}
-          role-duration-seconds: 2400
-          role-session-name: ${{ github.event.repository.name }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-
-      - name: Pull the docker image
-        run:
-          docker pull --platform=linux/amd64 "${{ matrix.artifact_name }}"
+          image_name: "${{ matrix.artifact_name }}"
 
       - name: Get the .snyk file
         run: |
@@ -119,6 +108,13 @@ jobs:
             --policy-path="${SNYK_POLICY_FILENAME}"
             --sarif
             --sarif-file-output="${SNYK_SARIF_FILENAME}"
+
+      - name: Fail if the sarif file is not created
+        run: |
+          if ! test -f "${SNYK_SARIF_FILENAME}" ; then
+            echo "ERROR: ${SNYK_SARIF_FILENAME} was not created"
+            exit 43
+          fi
 
       - name: Setup Kosli CLI
         if: ${{ success() || failure() }}
